### ISSUE TITLE
new error on master?

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit-models#74]
I was running fixdes most of the day and just pulled and installed master. I'm now getting this error

'''Traceback (most recent call last):
  File "C:/Users/mayork/Documents/GitHub/gpkit-models/gpkitmodels/Commercial Sizing/test.py", line 377, in <module>
    m = CommercialAircraft()
  File "C:/Users/mayork/Documents/GitHub/gpkit-models/gpkitmodels/Commercial Sizing/test.py", line 351, in __init__
    cmc = CommericalMissionConstraints(1)
  File "C:/Users/mayork/Documents/GitHub/gpkit-models/gpkitmodels/Commercial Sizing/test.py", line 191, in __init__
    Model.__init__(self, W_ftotal, constraints, **kwargs)
  File "c:\users\mayork\documents\github\gpkit\gpkit\constraints\model.py", line 65, in __init__
    self._add_modelname_tovars(self.name, self.num)
  File "c:\users\mayork\documents\github\gpkit\gpkit\constraints\model.py", line 100, in _add_modelname_tovars
    self.subinplace(add_model_subs)
  File "c:\users\mayork\documents\github\gpkit\gpkit\constraints\costed.py", line 25, in subinplace
    ConstraintSet.subinplace(self, subs, value)
  File "c:\users\mayork\documents\github\gpkit\gpkit\constraints\set.py", line 128, in subinplace
    constraint.subinplace(subs, value)
  File "c:\users\mayork\documents\github\gpkit\gpkit\nomials\nomial_math.py", line 442, in subinplace
    nomial.subinplace(substitutions, value)
AttributeError: 'list' object has no attribute 'subinplace' '''

I think its an error on master that occured after merging fixdes because I pulled and installed nomialmap and I could run the code fine

**Comment by mayork** [comment]
crap this models not normal gpkit
